''' Harcoded HTML ''' 
dashboard_html = 'dashboard.html'
edit_proj = 'edit_project.html'
edit_task = 'edit_task.html'
login = 'login.html'
projects = 'projects.html'
sign_up = 'sign_up.html'
view_project = 'view_project.html'
view_task = 'view_task.html'